version: "3.8"

services:
  app:
    build: .
    container_name: springboot-container
    tty: true
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/reservation?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: reservation2580!
    depends_on:
      - mysql
    networks:
      - springboot-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: reservation2580!
      MYSQL_DATABASE: reservation
      MYSQL_USER: msy
      MYSQL_PASSWORD: reservation2580!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springboot-network

networks:
  springboot-network:
    driver: bridge

volumes:
  mysql_data:
